# Generated by Django 5.1.1 on 2026-07-31 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше 1 минуты.'), django.core.validators.MaxValueValidator(32767, 'Время приготовления не может превышать 32767 минут.')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
