# Generated by Django 5.1.1 on 2026-07-22 19:52

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images/', validators=[recipes.validators.validator_image_size], verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
