# Generated by Django 5.1.1 on 2026-07-23 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у пользователей'),
        ),
    ]
